sudo: required

services: docker

before_install:
  - docker login -u matsuotakuro -p bfe21f01-e74f-41e6-b0e2-48aec1358223
  - docker-compose up --build -d

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test
